source "https://supermarket.chef.io"

cookbook "apt"
cookbook "ubuntu"
cookbook "build-essential"
cookbook "ntp"
cookbook "git"
cookbook "rvm", github: "martinisoft/chef-rvm"
cookbook "mono", github: "Youscribe/cookbook-mono"
cookbook "fsharp", path: "~/development/cookbooks/fsharp"
cookbook "dotfiles", path: "~/development/cookbooks/dotfiles"
cookbook "apache_spark"
cookbook "hadoop"
cookbook "eventstore"
cookbook "scala"
cookbook "java"
cookbook "simple-scala-sbt"
cookbook "anaconda"
